require 'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "bash",
        "c_sharp",
        "cmake",
        "comment",
        "cpp",
        "css",
        "fish",
        "go",
        "haskell",
        "html",
        "http",
        "javascript",
        "json5",
        "latex",
        "llvm",
        "lua",
        "make",
        "norg",
        "python",
        "regex",
        "rust",
        "solidity",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "zig",
    },
    highlight = {
        enable = true,
        disable = {},
    },
    indent = {
        enable = true
    }
}
