-- require("neotest").setup({
--     adapters = {
--         require("neotest-dotnet")({
--             custom_attributes = {
--                 nunit = { "TestCaseSource" },
--             },
--             -- Tell neotest-dotnet to use either solution (requires .sln file) or project (requires .csproj or .fsproj file) as project root
--             -- Note: If neovim is opened from the solution root, using the 'project' setting may sometimes find all nested projects, however,
--             --       to locate all test projects in the solution more reliably (if a .sln file is present) then 'solution' is better.
--             discovery_root = "solution",
--         }),
--     },
-- })
--
-- local opts = { noremap = true, silent = true }
-- vim.keymap.set("n", "<leader>tt", require("neotest").run.run, opts)
-- vim.keymap.set("n", "<leader>to", require("neotest").output_panel.toggle, opts)
-- vim.keymap.set("n", "<leader>ts", require("neotest").summary.toggle, opts)
-- vim.keymap.set("n", "<leader>tf", function()
--     require("neotest").run.run(vim.fn.expand("%"))
-- end, opts)
