return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		"nvim-treesitter/playground",
	},
	build = function() vim.cmd([[TSUpdate]]) end,
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"c_sharp",
				"go",
				"rust",
				"c",
				"css",
				"diff",
				"dockerfile",
				"bash",
				"git_rebase",
				"git_config",
				"gitignore",
				"gitcommit",
				"gomod",
				"gosum",
				"gowork",
				"html",
				"jsdoc",
				"json",
				"json5",
				"jsonc",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"python",
				"regex",
				"rust",
				"sql",
				"svelte",
				"vim",
				"vimdoc",
				"vue",
				"yaml",
				"zig",
			},
			sync_install = false,
			auto_install = false,
			ignore_install = {},
			modules = {},
			highlight = {
				enable = true,
				disable = { "dockerfile" },
			},
			indent = { enable = true },
		})
	end,
}
