return {
	"nvim-treesitter/nvim-treesitter",
	dependencies = {
		{ "nvim-treesitter/playground" },
		{ "nushell/tree-sitter-nu" },
	},
	build = function() vim.cmd([[TSUpdate]]) end,
	config = function()
		require("nvim-treesitter.install").compilers = { "clang", "gcc", "zig" }
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"angular",
				"bash",
				"c",
				"c_sharp",
				"css",
				"diff",
				"dockerfile",
				"git_config",
				"git_rebase",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gowork",
				"html",
				"jsdoc",
				"json",
				"json5",
				"jsonc",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"nu",
				"python",
				"regex",
				"rust",
				"sql",
				"vim",
				"vimdoc",
				"vue",
				"yaml",
				"zig",
			},
			sync_install = true,
			auto_install = true,
			ignore_install = {},
			modules = {},
			highlight = {
				enable = true,
				disable = { "dockerfile" },
			},
			indent = { enable = true },
		})
	end,
}
